[package]
name = "pomodors"
version = "0.1.0"
edition = "2024"

[dependencies]
notify-rust = "4.12.0"
tui = "0.19.0"
crossterm = "0.29"
figlet-rs = "0.1.5"
clap = {version = "4.5.50", features = ["derive"]}
